### PR TITLE
added feed forward tracks to messaging

### PR DESCRIPTION
**Pull request by clnowacki**
Added optional feed-forward locations/tracks to the Java job definitions and job requests.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-java-component-sdk/7)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFAudioJob.java, line 50 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkBdDfZr4EDKDg71hh:-KqkBdDfZr4EDKDg71hi:b-j3346g) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFAudioJob.java#L50)):*
> ```Java
>      */
>     public boolean hasFeedForwardTrack() {
> 	return hasFeedForwardTrack;
> ```

Please check left indentation here and for the other lines you added.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 40 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkC10qXACYitPTARz4:-KqkC10qXACYitPTARz5:b14eq1s) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L40)):*
> ```Java
>     private final int startFrame;
>     private final int stopFrame;
>     private final boolean hasFeedForwardTrack;
> ```

Do we want a flag for this or is it acceptable to just check if feedForwardTrack is null? The same kind of question applies to audio and image jobs.

@brosenberg42, do you have an opinion?

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 64 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkCGaiN0ErVNF1JMsb:-KqkCGaiN0ErVNF1JMsc:b7n4y6w) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L64)):*
> ```Java
> 
>     /**
>      *  A VideoJob may contain a feed-forward track from a previous stage
> ```

Say "video job" to be consistent with other comments.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 74 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkCKVR_EgwzMwxGsEt:-KqkCKVR_EgwzMwxGsEu:b7n4y6w) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L74)):*
> ```Java
> 
>     /**
>      *  A VideoJob may contain a feed-forward track from a previous stage
> ```

Say "video job" to be consistent with other comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Comment by jrobble** [comment]
*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 40 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkC10qXACYitPTARz4:-KqxAh--HzpCGzNcf4gM:b51bgop) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L40)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we want a flag for this or is it acceptable to just check if feedForwardTrack is null? The same kind of question applies to audio and image jobs.

@brosenberg42, do you have an opinion?
</blockquote></details>

I understand the need for this flag on the C++ side, but I think there is a stronger argument to check for null in Java since that seems more typical.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFAudioJob.java, line 50 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkBdDfZr4EDKDg71hh:-Kr10FkR3BkAYDMV232S:b-896fix) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFAudioJob.java#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please check left indentation here and for the other lines you added.
</blockquote></details>

Done.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 64 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkCGaiN0ErVNF1JMsb:-Kr10hp8pjTF9jRbVdXm:b-896fix) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L64)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Say "video job" to be consistent with other comments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Comment by jrobble** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java, line 40 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7#-KqkC10qXACYitPTARz4:-Kr6Cq2iAjwSlTniRDkg:b-52o1el) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/27ab978c1f815a3fd0d0134a20d79ce80c814eef/detection/java-component-api/src/main/java/org/mitre/mpf/component/api/MPFVideoJob.java#L40)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I understand the need for this flag on the C++ side, but I think there is a stronger argument to check for null in Java since that seems more typical.
</blockquote></details>

As agreed, I will remove the boolean flag and simply test whether the feedForwardTrack is NULL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Comment by jrobble** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/7)*

**Review by jrobble — APPROVED** [review]

**Pull request merged**
