### PR TITLE
 Added support for generic detections.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-java-component-sdk/17)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Sphinx needs to be updated.

---

Reviewed 23 of 29 files at r1.
Review status: 16 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyILgmXTkR-Czi2h5WO:b40lykh)*

**Comment by jrobble** [comment]
Sphinx is part of the openmpf-components repo. It uses the `MPFAudioAndVideoDetectionComponentAdapter` in this class, which has been updated with:

```
    public List<MPFGenericTrack> getDetections(MPFGenericJob job) throws MPFComponentDetectionError {
        throw new MPFComponentDetectionError(MPFDetectionError.MPF_UNSUPPORTED_DATA_TYPE, "Generic detection not supported.");
    }
```

Does anything else need to be done?

---

Review status: 16 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyIRmnCyZ7_8uSmz-Sa:bpzmnmm)*

**Comment by jrobble** [comment]
* It uses the `MPFAudioAndVideoDetectionComponentAdapter` in this **repo** ...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyISMYZPqFnoOT3_FW6:b-7z9wq8)*

**Comment by brosenberg42** [comment]
You changed the package of MPFAudioAndVideoDetectionComponentAdapter and a few other classes. Sphinx is importing from the wrong package.

---

Review status: 16 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyISfJy9zYdxlhZnJNl:b-p6rhyj)*

**Comment by jrobble** [comment]
You're right. I made that change but didn't create a PR for that repo. Will do.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyITHaEhoHHP_NHKFyW:b-u3oo8)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 6 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/17#-:-KyM4Ma7-IhxeJVC8dQp:bnfp4nl)*

**Review by brosenberg42 — APPROVED** [review]

**Pull request merged**
