### PR TITLE
Adding HelloWorld and AudioVideoComponent java examples.

### PR DESCRIPTION
**Pull request by bccole**
Adding two example components in Java.  HelloWorld is the most basic component.  AudioVideoComponent adds logging, an adapter, and a third-party library.

To test, confirm that the components compile, package, and deploy.  Test on various media types (AudioVideoComponent should fail on image files.)

Verify that comments are descriptive and helpful in understanding the development of a component.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-java-component-sdk/1)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pom.xml, line 42 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlYwVrnP4RovuBGjaqv:-KlYwVroSxq_-kBhJQB-:b4z57c4) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/pom.xml#L42)):*
> ```XML
>         <module>audio-video-utils</module>
>         <module>java-component-api</module>
>         <module>examples</module>
> ```

I'm not sure whether or not  we should build the examples by default.

---

*[examples/AudioVideoComponent/pom.xml, line 63 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlYvElEqkM_BupdIg5D:-KlYvElFJkQ7cfTJ7n_g:b-qo7yhz) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/AudioVideoComponent/pom.xml#L63)):*
> ```XML
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-dependency-plugin</artifactId>
> ```

This plugin isn't necessary. The `assemblyDescriptor.xml`'s `<dependencySet>` element takes care of pulling the in the dependencies. When I remove this plugin, the .tar.gz file contains the same content.

---

*[examples/HelloWorld/pom.xml, line 53 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlYzdxSVUSM9m-g8-w7:-KlYzdxSVUSM9m-g8-w8:bsxd21d) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/HelloWorld/pom.xml#L53)):*
> ```XML
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-dependency-plugin</artifactId>
> ```

This plugin isn't necessary. The `assemblyDescriptor.xml`'s `<dependencySet>` element takes care of pulling the in the dependencies. When I remove this plugin, the .tar.gz file contains the same content.

---

*[examples/HelloWorld/src/test/java/org/mitre/mpf/examples/hello/HelloWorldComponentTest.java, line 55 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZ02CfHPPOI0qphsdA:-KlZ02CfHPPOI0qphsdB:b-3i5luv) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/HelloWorld/src/test/java/org/mitre/mpf/examples/hello/HelloWorldComponentTest.java#L55)):*
> ```Java
>  * the init() or close() methods are overridden, those also should be tested.
>  */
> public class HelloWorldComponentTest  extends TestCase {
> ```

This shouldn't extend TestCase. TestCase is how you would write tests for JUnit3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Comment by jrobble** [comment]
Dropping comments for visual code review. I still need to run these.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pom.xml, line 42 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlYwVrnP4RovuBGjaqv:-KlZKl4inY1sgDEkX1d6:bvpsuvx) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/pom.xml#L42)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I'm not sure whether or not  we should build the examples by default.
</blockquote></details>

I think we should for regression testing. I don't want the examples to fall behind the component API if there are changes. The amount of time it takes to build the examples is so minimal I don't think it's worth being too concerned about adding an option to disable that part of the build. We can do that in the future if we think it's worth it. 

---

*[examples/pom.xml, line 37 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZP9im5UaOVkG-05K-:-KlZP9im5UaOVkG-05K0:b67mmr8) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/pom.xml#L37)):*
> ```XML
>     <artifactId>openmpf-java-component-examples</artifactId>
>     <packaging>pom</packaging>
>     <name>OpenMPF Java Component SDK</name>
> ```

This name shows up twice in the build:

```
[INFO] OpenMPF Java Component SDK ......................... SUCCESS [  0.510 s]
[INFO] OpenMPF Audio-Video Utils .......................... SUCCESS [  2.423 s]
[INFO] OpenMPF Java Component API ......................... SUCCESS [  1.785 s]
[INFO] mpf-java-example-audiovideo ........................ SUCCESS [  3.944 s]
[INFO] mpf-java-example-helloworld ........................ SUCCESS [  1.180 s]
[INFO] OpenMPF Java Component SDK ......................... SUCCESS [  0.007 s]
```

Please change it to "OpenMPF Java Component Examples".

---

*[examples/AudioVideoComponent/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZMqaThCH0sCIC76jy:-KlZMqaThCH0sCIC76jz:b27mrtp) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/AudioVideoComponent/pom.xml#L12)):*
> ```XML
>     <modelVersion>4.0.0</modelVersion>
> 
>     <artifactId>mpf-java-example-audiovideo</artifactId>
> ```

Sphinx is "mpf-sphinx-speech-detection-component". Let's call this "mpf-audiovideo-java-example-component" for consistency.

---

*[examples/AudioVideoComponent/plugin-files/logback.xml, line 31 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZXWx0Xl4E6pMyrIUV:-KlZXWx0Xl4E6pMyrIUW:b-6n6hoe) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/AudioVideoComponent/plugin-files/logback.xml#L31)):*
> ```XML
>     <if condition='isNull("audioVideoExampleDetectionLogFile")' >
>         <then>
>             <property name="audioVideoExampleDetectionLogFile" value="${MPF_LOG_PATH}/${THIS_MPF_NODE}/log/audiovideo-example-detection.log" />
> ```

Please name this "audiovideo-java-example-detection.log". The "java" is important to differentiate it from C++.

Also, change "audioVideoExampleDetectionLogFile" to "audioVideoJavaExampleDetectionLogFile" and change "AUDIOVIDEO-EXAMPLE-DETECTION-FILE" to "AUDIOVIDEO-JAVA-EXAMPLE-DETECTION-FILE"

---

*[examples/AudioVideoComponent/src/main/java/org/mitre/mpf/examples/audiovideo/AudioVideoComponent.java, line 98 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZ_0H549dRICDg7Ks6:-KlZ_0H549dRICDg7Ks7:byu22fg) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/AudioVideoComponent/src/main/java/org/mitre/mpf/examples/audiovideo/AudioVideoComponent.java#L98)):*
> ```Java
> 
>     public String getDetectionType() {
>         return "HELLO";
> ```

This should be "AUDIOVIDEO" to differentiate it from the HelloWorldComponent.

---

*[examples/HelloWorld/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZNrClNLg1RXVEGEa5:-KlZNrClNLg1RXVEGEa6:bia8soa) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/HelloWorld/pom.xml#L12)):*
> ```XML
>     <modelVersion>4.0.0</modelVersion>
> 
>     <artifactId>mpf-java-example-helloworld</artifactId>
> ```

Sphinx is "mpf-sphinx-speech-detection-component". Let's call this "mpf-helloworld-java-example-component" for consistency.

The name of this directory should be openmpf-java-component-sdk/examples/HelloWorldComponent so that it's consistent with the "HelloWorldComponent" in openmpf-cpp-component-sdk/detection/examples/HelloWorldComponent.

---

*[examples/HelloWorld/src/test/java/org/mitre/mpf/examples/hello/HelloWorldComponentTest.java, line 109 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlZ_NJ3Nsy3z8_nfEWf:-KlZ_NJ3Nsy3z8_nfEWg:bwgaser) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/examples/HelloWorld/src/test/java/org/mitre/mpf/examples/hello/HelloWorldComponentTest.java#L109)):*
> ```Java
>     @Test
>     public void testGetDetectionsVideo() throws Exception {
>         String uri = "RandomImageFile";
> ```

Should be "RandomVideoFile".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-:-KlZ_fU27AMPMkAhOgNf:bu0daeo)*

**Comment by jrobble** [comment]
*[pom.xml, line 42 at r1](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KlYwVrnP4RovuBGjaqv:-KlZfdoBOiZo74mjKlbu:b-75pvhr) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/20b7206ee387f529cfe19a5321ff3915dbf9e4d8/pom.xml#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should for regression testing. I don't want the examples to fall behind the component API if there are changes. The amount of time it takes to build the examples is so minimal I don't think it's worth being too concerned about adding an option to disable that part of the build. We can do that in the future if we think it's worth it. 
</blockquote></details>

@brosenberg42, similarly, I think the C++ examples should be built by default for regression purposes. Can you make that change? If you think the packaging step takes too long, feel free to add an option to enable/disable it. Jenkins should enable it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Comment by jrobble** [comment]
The C++ example component packages are named: AudioOnlyComponent.tar.gz, FrameDataComponent.tar.gz, HelloWorldComponent.tar.gz, VideoCaptureComponent.tar.gz. They should really have "C++" or "CPP" in there, in addition to "Example", but that's a separate issue (https://github.com/openmpf/openmpf/issues/89).

These Java example component packages are named: AudioVideoExample.tar.gz ﻿and HelloWorld.tar.gz. Please rename them to: AudioVideoJavaExampleComponent.tar.gz ﻿and HelloWorldJavaExampleComponent.tar.gz.

The name of the default pipeline in the pipelines dropdown and name of the component on the Nodes page should be updated as well. I think if you change the name in the descriptor.json file that's all you need to do.

**Review by jrobble — CHANGES_REQUESTED** [review]
The test outputs are as follows:

```
Running org.mitre.mpf.examples.audiovideo.AudioVideoComponentTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Number of audio tracks = 1.
Audio track number 0
  start time = 10000
  stop time = 10001
  confidence = 0.800000
  metadata = extra audio track info
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.077 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

```
Running org.mitre.mpf.examples.hello.HelloWorldComponentTest
[TestAudioJob] Processing RandomAudioFile from start time 10000 ms to stop time 19999 ms.
[TestAudioJob] Processing complete. Generated 1 dummy audio tracks.
Number of audio tracks = 1.
Audio track number 0
  start time = 10000
  stop time = 10001
  confidence = 0.800000
  metadata = extra audio track info
[TestImageJob] Processing RandomImageFile.
[TestImageJob] Processing complete. Generated 1 dummy image locations.
Number of image locations = 1.
Image location number 0
  x left upper = 0
  y left upper = 0
  width = 100
  height = 100
  confidence = 0.800000
  metadata = extra image location info
[TestVideoJob] Processing RandomImageFile from frame 100 to frame 199.
[TestVideoJob] Job properties contains FRAME_INTERVAL with a value of 5.
[TestVideoJob] Processing complete. Generated 1 dummy video tracks.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.118 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

Some of the tests have `System.out.println()` lines while others don't. For consistency, please add them to all of the tests.

Overall, the code is well documented and the tests cover the code well.

**Comment by jrobble** [comment]
Also, note that when we land this the following text on the https://openmpf.github.io/docs/site/Java-Component-API/ page needs to be updated:

> (examples shown; TODO: implement these)

**Comment by jrobble** [comment]
Review status: 3 of 15 files reviewed at latest revision, 12 unresolved discussions.

---

*[examples/AudioVideoComponent/plugin-files/descriptor/descriptor.json, line 10 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KldQHdEv-nEGlULTw2Q:-KldQHdF0HIQPHH6kwhd:btr3lkj) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/1f11f2c45fc3e342246ef3248de62769eca7a93a/examples/AudioVideoComponent/plugin-files/descriptor/descriptor.json#L10)):*
> ```JSON
>   "environmentVariables" : [],
>   "algorithm" : {
>     "name": "AudioVideo",
> ```

Please change this to "JavaAudioVideo".

---

*[examples/HelloWorldComponent/plugin-files/descriptor/descriptor.json, line 10 at r2](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-KldQO0JGbBy7yN7_USP:-KldQO0JGbBy7yN7_USQ:b-3xpulu) ([raw file](https://github.com/openmpf/openmpf-java-component-sdk/blob/1f11f2c45fc3e342246ef3248de62769eca7a93a/examples/HelloWorldComponent/plugin-files/descriptor/descriptor.json#L10)):*
> ```JSON
>   "environmentVariables" : [],
>   "algorithm" : {
>     "name": "HelloWorld",
> ```

Please change this to "JavaHelloWorld".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Comment by brosenberg42** [comment]
Reviewed 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 1 of 18 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-:-KlsHmt5ZBgaNuq_L-pu:bnfp4nl)*

**Review by brosenberg42 — DISMISSED** [review]

**Comment by jrobble** [comment]
Reviewed 16 of 18 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Comment by jrobble** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1#-:-KlskNEA-Zz62yhFBXmN:bnfp4nl)*

**Review by jrobble — DISMISSED** [review]

**Comment by jrobble** [comment]
Also, please remove:

`<module>examples</module`

from openmpf-java-component-sdk/pom.xml.

Thanks for bearing with us while we're figuring out the best way to do things.

**Review by brosenberg42 — APPROVED** [review]

**Review by jrobble — CHANGES_REQUESTED** [review]
“openmpf-java-component-sdk/examples” should be “openmpf-java-component-sdk/detection/examples" to be consistent with the C++ SDK.

Also, please remove:

`<module>examples</module>`

**Comment by jrobble** [comment]
Reviewed 6 of 30 files at r2, 28 of 29 files at r4, 61 of 61 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf-java-component-sdk/1)*

**Review by jrobble — APPROVED** [review]

**Pull request merged**
